name: 'Main pipeline'

on: push

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
  APPLICATION_NAME: "parking-application"

jobs:
    terraform:
        name: 'Terraform test'
        environment: 'dev'
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps: 
        # Checkout repo to Github Actions runner
        - name: Checkout
          uses: actions/checkout@v4.1.1
        
        # Setup Terraform into the runner
        - name: Setup terraform
          uses: hashicorp/setup-terraform@v1
        
        # Initialize Terraform
        - name: Terraform init
          run: terraform init
        
        # Check format to canonical (Prevents reading issues in ubuntu)
        - name: Terraform format
          run: terraform -fmt check
        
        # Terraform plan
        - name: Terraform plan
          run: terraform plan
    
    deploy:
        name: 'Deploy infrastructure'
        runs-on: ubuntu-latest
        environment: 'prod'
        needs: [ terraform ]
        defaults:
          run:
              shell: bash
        steps:
        # Terraform apply
        - id: terraform-apply
          name: Terraform apply
          run: terraform apply -auto-approve -input=false
        
        # Terraform outputs
        - id: terraform-outputs
          name: Terraform outputs
          run: |
            echo "ARTIFACT_REGISTRY=$(terraform output -raw artifact_registry_id)" >> $GITHUB_OUTPUT
          working-directory: ./terraform
      
    application:
        name: 'Deploy application'
        runs-on: ubuntu-latest
        environment: 'dev'
        needs: [ deploy ]
        defaults:
            run:
                shell: bash
        steps:
        # Build the Docker image of the application
        - name: Build image
          run: docker build . \
            -t ${{ env.APPLICATION_NAME }} \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF"
          working-directory: ./app

        # Push the Docker image to Google Container Registry
        - name: Publish
          run: docker push ${{ steps.terraform_outputs.outputs.ARTIFACT_REGISTRY }}
        
        # Quickly install kustomize (~25mb)
        - name: Install Kustomize
          run: |
            curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
            chmod u+x ./kustomize