name: 'Main pipeline'

on: [workflow_call, push]

env:
  TF_VARS: ${{ secrets.TF_VARS }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
  APPLICATION_NAME: "parking-application"
  DEFAULT_REGION: "us-central1"

jobs:
    terraform:
        name: 'Terraform test'
        environment: 'dev'
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps: 
        # Checkout repo to Github Actions runner
        - name: Checkout
          uses: actions/checkout@v4.1.1
        
        # Log in with secret
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ env.GOOGLE_APPLICATION_CREDENTIALS }}'
        
        # Setup Terraform into the runner
        - name: Setup terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_wrapper: false

        # Iterate through each variable on secret tfvars and reformat data if needed. 
        # Importing .tfvars from secret drops the values double quotes, a regex solve the issue adding them back! Also, after formatting, the values matches exactly the secrets thus is hidden from action logs. Great.
        - name: Variable iteration
          run: for v in "${{ secrets.TF_VARS }}"; do echo -e "$v" | sed 's/\(=[[:blank:]]*\)\(.*\)/\1"\2"/' >> terraform.tfvars; done
        
        # Initialize Terraform
        - name: Terraform init
          run: terraform init
        
        # Format and check terraform files to canonical (Prevents reading issues in ubuntu, specially with the new .tfvars file)
        - name: Terraform format check
          if: success() || failure()
          run: |
            terraform fmt
            terraform fmt -check
        
        # Terraform validate
        - name: Terraform validate
          if: success() || failure()
          run:  terraform validate -no-color

        # Terraform plan
        - name: Terraform plan
          run: terraform plan -input=false --var-file=terraform.tfvars -out=tfplan
        
        # Save plan as Artifact
        - name: Plan artifact
          uses: actions/upload-artifact@v2
          with:
            name: plan-artifact
            path: tfplan
    
    infrastructure:
        name: 'Deploy infrastructure'
        runs-on: ubuntu-latest
        environment: 'prod'
        needs: [ terraform ]
        defaults:
          run:
              shell: bash
        steps:
        # Checkout repo to Github Actions runner
        - name: Checkout
          uses: actions/checkout@v4.1.1
        
        # Log in with secret
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ env.GOOGLE_APPLICATION_CREDENTIALS }}'
        
        # Setup Terraform into the runner
        - name: Setup terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_wrapper: false

        # Re-initialize Terraform
        - name: Terraform init
          run: terraform init
        
        # Download plan from Artifact
        - uses: actions/download-artifact@v2
          with:
            name: plan-artifact

        # Check tfplan
        - name: Check tfplan
          run: terraform show tfplan
        
        # Terraform apply
        - id: terraform-apply
          name: Terraform apply
          run: terraform apply -auto-approve -input=false tfplan
        
        # Terraform outputs
        - id: terraform-outputs
          name: Terraform outputs
          run: |
            echo "ARTIFACT_REGISTRY=$(terraform output -raw artifact-registry-path)" >> $GITHUB_OUTPUT
            echo "SHORT_ARTIFACT_REGISTRY=$(terraform output -raw artifact-registry-short-path)" >> $GITHUB_OUTPUT
            echo "MAIN_GKE_CLUSTER=$(terraform output -raw main_gke_cluster)" >> $GITHUB_OUTPUT
          working-directory: ./terraform
      
    application:
        name: 'Load application'
        runs-on: ubuntu-latest
        environment: 'dev'
        needs: [ infrastructure ]
        defaults:
            run:
                shell: bash
        steps:
        # Checkout repo to Github Actions runner
        - name: Checkout
          uses: actions/checkout@v4.1.1
        
        # Log in with secret
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ env.GOOGLE_APPLICATION_CREDENTIALS }}'
        
        # Build the Docker image of the application
        - name: Build image
          run: docker build . \
            -t ${{ env.APPLICATION_NAME }} \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF"
          working-directory: ./app/${{ env.APPLICATION_NAME }}

        # Configure local Docker client
        - name: Configure Docker
          run: gcloud auth configure-docker ${{ steps.terraform_outputs.outputs.SHORT_ARTIFACT_REGISTRY }}
        
        # Push the Docker image to Artifact Registry
        - name: Publish
          run: |
            docker tag ${{ env.APPLICATION_NAME }} ${{ steps.terraform_outputs.outputs.ARTIFACT_REGISTRY }}/${{ env.APPLICATION_NAME }}
            docker push ${{ steps.terraform_outputs.outputs.ARTIFACT_REGISTRY }}/${{ env.APPLICATION_NAME }}
      
    deploy:
        name: 'Deploy application'
        runs-on: ubuntu-latest
        environment: 'prod'
        needs: [ infrastructure, application ]
        defaults:
          run:
              shell: bash
        steps:
        # Checkout repo to Github Actions runner
        - name: Checkout
          uses: actions/checkout@v4.1.1
        
        # Log in with secret
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ env.GOOGLE_APPLICATION_CREDENTIALS }}'

        # Catch existing cluster
        - name: Catch existing cluster
          run: gcloud container clusters get-credentials ${{ steps.terraform_outputs.outputs.MAIN_GKE_CLUSTER }} --location ${{ env.DEFAULT_REGION }}

        # Deploy on GKE
        - name: Deploy on GKE
          run: kubectl create deployment ${{ env.APPLICATION_NAME }} --image=${{ steps.terraform_outputs.outputs.ARTIFACT_REGISTRY }}/${{ env.APPLICATION_NAME }}

        # Expose cluster
        - name:
          run: kubectl expose deployment ${{ env.APPLICATION_NAME }} \
            --type LoadBalancer \
            --port 80 \
            --target-port 5003